ses_api_mailer.settings:
  type: config_object
  label: 'SES API Mailer settings'
  mapping:
    previous_mailer:
      type: string
      label: 'Mailer used before SES API Mailer was enabled'
    previous_mailsystem_sender:
      type: string
      label: 'Mailsystem sender used before SES API Mailer was enabled'
    previous_mailsystem_formatter:
      type: string
      label: 'Mailsystem formatter used before SES API Mailer was enabled'
    daily_send_limit:
      type: integer
      label: 'Maximum SES recipients per day'
    alert_recipients:
      type: string
      label: 'Recipients for SES daily usage alerts'
